import { describe, expect, it } from 'vitest';
import {
  expectKeyedStringArrayDomains,
  expectKeyedStringRecordDomains,
  expectNonEmptyString,
  expectObjectKeyDomainParity,
  expectNonEmptyUniqueStringArray
} from './compat-contract-assertion-test-utils.js';
import {
  REQUIRED_COMPAT_CI_JOB_NAME,
  REQUIRED_COMPAT_CI_JOB_NAMES,
  REQUIRED_COMPAT_CI_JOB_FIELD_NAME_SEQUENCES,
  REQUIRED_COMPAT_CI_JOB_TOP_LEVEL_SCALAR_VALUE_CONTRACTS,
  REQUIRED_COMPAT_CI_JOB_STEP_NAME_SEQUENCES,
  REQUIRED_COMPAT_CI_JOB_UNIQUE_FIELD_NAME_SEQUENCES,
  REQUIRED_COMPAT_CI_JOB_RUNS_ON,
  REQUIRED_COMPAT_CI_JOB_TIMEOUT_MINUTES,
  REQUIRED_COMPAT_CI_JOB_FIELD_NAMES,
  REQUIRED_COMPAT_CI_JOB_UNIQUE_FIELD_NAMES,
  REQUIRED_COMPAT_CI_CHECKOUT_STEP_NAME,
  REQUIRED_COMPAT_CI_CHECKOUT_USES,
  REQUIRED_COMPAT_CI_FAILURE_UPLOAD_ARTIFACT_NAME,
  REQUIRED_COMPAT_CI_FAILURE_UPLOAD_CONDITION,
  REQUIRED_COMPAT_CI_FAILURE_UPLOAD_IF_NO_FILES_FOUND,
  REQUIRED_COMPAT_CI_FAILURE_UPLOAD_PATH,
  REQUIRED_COMPAT_CI_FAILURE_UPLOAD_STEP_NAME,
  REQUIRED_COMPAT_CI_FAILURE_UPLOAD_USES,
  REQUIRED_COMPAT_CI_WORKFLOW_NAME,
  REQUIRED_COMPAT_CI_WORKFLOW_FIELD_NAMES,
  REQUIRED_COMPAT_CI_WORKFLOW_UNIQUE_FIELD_NAMES,
  REQUIRED_COMPAT_CI_TRIGGER_PUSH_BRANCHES,
  REQUIRED_COMPAT_CI_TRIGGER_NAMES,
  REQUIRED_COMPAT_CI_TRIGGER_SECTION_FIELD_NAME_SEQUENCES,
  REQUIRED_COMPAT_CI_INSTALL_COMMAND,
  REQUIRED_COMPAT_CI_INSTALL_STEP_NAME,
  REQUIRED_COMPAT_CI_PRIMARY_RUN_COMMAND,
  REQUIRED_COMPAT_CI_REPORT_DIR_ENV_KEY,
  REQUIRED_COMPAT_CI_REPORT_DIR_ENV_VALUE,
  REQUIRED_COMPAT_CI_SETUP_NODE_CACHE,
  REQUIRED_COMPAT_CI_SETUP_NODE_STEP_NAME,
  REQUIRED_COMPAT_CI_SETUP_NODE_USES,
  REQUIRED_COMPAT_CI_SETUP_NODE_VERSION,
  REQUIRED_COMPAT_CI_STEP_ENV_SCALAR_VALUE_CONTRACTS,
  REQUIRED_COMPAT_CI_STEP_TOP_LEVEL_SCALAR_VALUE_CONTRACTS,
  REQUIRED_COMPAT_CI_STEP_WITH_SCALAR_VALUE_CONTRACTS,
  REQUIRED_COMPAT_CI_STEP_ENV_FIELD_NAME_SEQUENCES,
  REQUIRED_COMPAT_CI_STEP_WITH_FIELD_NAME_SEQUENCES,
  REQUIRED_COMPAT_CI_STEP_FIELD_NAME_SEQUENCES,
  REQUIRED_COMPAT_CI_STEP_NAMES,
  REQUIRED_COMPAT_CI_STEP_SEQUENCE,
  REQUIRED_COMPAT_CI_PRIMARY_RUN_STEP_NAME,
  REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_NAME,
  REQUIRED_COMPAT_CI_UPLOAD_CONDITION,
  REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_FILES,
  REQUIRED_COMPAT_CI_UPLOAD_IF_NO_FILES_FOUND,
  REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_PATH_PREFIX,
  REQUIRED_COMPAT_CI_UPLOAD_STEP_NAME,
  REQUIRED_COMPAT_CI_UPLOAD_USES
} from './compat-npm-script-contracts.mjs';

describe('compat ci workflow contracts constants', () => {
  it('keeps required ci workflow string contracts non-empty', () => {
    const requiredScalarStringContracts = [
      [REQUIRED_COMPAT_CI_PRIMARY_RUN_STEP_NAME, 'REQUIRED_COMPAT_CI_PRIMARY_RUN_STEP_NAME'],
      [REQUIRED_COMPAT_CI_PRIMARY_RUN_COMMAND, 'REQUIRED_COMPAT_CI_PRIMARY_RUN_COMMAND'],
      [REQUIRED_COMPAT_CI_UPLOAD_STEP_NAME, 'REQUIRED_COMPAT_CI_UPLOAD_STEP_NAME'],
      [REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_NAME, 'REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_NAME'],
      [REQUIRED_COMPAT_CI_UPLOAD_CONDITION, 'REQUIRED_COMPAT_CI_UPLOAD_CONDITION'],
      [REQUIRED_COMPAT_CI_UPLOAD_USES, 'REQUIRED_COMPAT_CI_UPLOAD_USES'],
      [REQUIRED_COMPAT_CI_UPLOAD_IF_NO_FILES_FOUND, 'REQUIRED_COMPAT_CI_UPLOAD_IF_NO_FILES_FOUND'],
      [REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_PATH_PREFIX, 'REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_PATH_PREFIX'],
      [REQUIRED_COMPAT_CI_REPORT_DIR_ENV_KEY, 'REQUIRED_COMPAT_CI_REPORT_DIR_ENV_KEY'],
      [REQUIRED_COMPAT_CI_REPORT_DIR_ENV_VALUE, 'REQUIRED_COMPAT_CI_REPORT_DIR_ENV_VALUE'],
      [REQUIRED_COMPAT_CI_FAILURE_UPLOAD_STEP_NAME, 'REQUIRED_COMPAT_CI_FAILURE_UPLOAD_STEP_NAME'],
      [REQUIRED_COMPAT_CI_FAILURE_UPLOAD_CONDITION, 'REQUIRED_COMPAT_CI_FAILURE_UPLOAD_CONDITION'],
      [REQUIRED_COMPAT_CI_FAILURE_UPLOAD_ARTIFACT_NAME, 'REQUIRED_COMPAT_CI_FAILURE_UPLOAD_ARTIFACT_NAME'],
      [REQUIRED_COMPAT_CI_FAILURE_UPLOAD_PATH, 'REQUIRED_COMPAT_CI_FAILURE_UPLOAD_PATH'],
      [REQUIRED_COMPAT_CI_FAILURE_UPLOAD_USES, 'REQUIRED_COMPAT_CI_FAILURE_UPLOAD_USES'],
      [REQUIRED_COMPAT_CI_FAILURE_UPLOAD_IF_NO_FILES_FOUND, 'REQUIRED_COMPAT_CI_FAILURE_UPLOAD_IF_NO_FILES_FOUND'],
      [REQUIRED_COMPAT_CI_WORKFLOW_NAME, 'REQUIRED_COMPAT_CI_WORKFLOW_NAME'],
      [REQUIRED_COMPAT_CI_CHECKOUT_STEP_NAME, 'REQUIRED_COMPAT_CI_CHECKOUT_STEP_NAME'],
      [REQUIRED_COMPAT_CI_CHECKOUT_USES, 'REQUIRED_COMPAT_CI_CHECKOUT_USES'],
      [REQUIRED_COMPAT_CI_JOB_NAME, 'REQUIRED_COMPAT_CI_JOB_NAME'],
      [REQUIRED_COMPAT_CI_JOB_RUNS_ON, 'REQUIRED_COMPAT_CI_JOB_RUNS_ON'],
      [REQUIRED_COMPAT_CI_JOB_TIMEOUT_MINUTES, 'REQUIRED_COMPAT_CI_JOB_TIMEOUT_MINUTES'],
      [REQUIRED_COMPAT_CI_SETUP_NODE_STEP_NAME, 'REQUIRED_COMPAT_CI_SETUP_NODE_STEP_NAME'],
      [REQUIRED_COMPAT_CI_SETUP_NODE_USES, 'REQUIRED_COMPAT_CI_SETUP_NODE_USES'],
      [REQUIRED_COMPAT_CI_SETUP_NODE_VERSION, 'REQUIRED_COMPAT_CI_SETUP_NODE_VERSION'],
      [REQUIRED_COMPAT_CI_SETUP_NODE_CACHE, 'REQUIRED_COMPAT_CI_SETUP_NODE_CACHE'],
      [REQUIRED_COMPAT_CI_INSTALL_STEP_NAME, 'REQUIRED_COMPAT_CI_INSTALL_STEP_NAME'],
      [REQUIRED_COMPAT_CI_INSTALL_COMMAND, 'REQUIRED_COMPAT_CI_INSTALL_COMMAND']
    ];
    for (const [value, label] of requiredScalarStringContracts) {
      expectNonEmptyString(value, label);
    }
    expectNonEmptyUniqueStringArray(
      REQUIRED_COMPAT_CI_WORKFLOW_UNIQUE_FIELD_NAMES,
      'REQUIRED_COMPAT_CI_WORKFLOW_UNIQUE_FIELD_NAMES'
    );
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_WORKFLOW_FIELD_NAMES, 'REQUIRED_COMPAT_CI_WORKFLOW_FIELD_NAMES');
    expect(REQUIRED_COMPAT_CI_WORKFLOW_FIELD_NAMES).toEqual(REQUIRED_COMPAT_CI_WORKFLOW_UNIQUE_FIELD_NAMES);
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_TRIGGER_PUSH_BRANCHES, 'REQUIRED_COMPAT_CI_TRIGGER_PUSH_BRANCHES');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_TRIGGER_NAMES, 'REQUIRED_COMPAT_CI_TRIGGER_NAMES');
    expectKeyedStringArrayDomains(
      REQUIRED_COMPAT_CI_TRIGGER_SECTION_FIELD_NAME_SEQUENCES,
      REQUIRED_COMPAT_CI_TRIGGER_NAMES,
      'REQUIRED_COMPAT_CI_TRIGGER_SECTION_FIELD_NAME_SEQUENCES',
      { requireExactKeyDomain: true, allowEmptyKeys: ['pull_request'] }
    );
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_JOB_NAMES, 'REQUIRED_COMPAT_CI_JOB_NAMES');
    expect(REQUIRED_COMPAT_CI_JOB_NAMES).toContain(REQUIRED_COMPAT_CI_JOB_NAME);
    expectKeyedStringArrayDomains(
      REQUIRED_COMPAT_CI_JOB_UNIQUE_FIELD_NAME_SEQUENCES,
      REQUIRED_COMPAT_CI_JOB_NAMES,
      'REQUIRED_COMPAT_CI_JOB_UNIQUE_FIELD_NAME_SEQUENCES',
      { requireExactKeyDomain: true }
    );
    expectKeyedStringArrayDomains(
      REQUIRED_COMPAT_CI_JOB_FIELD_NAME_SEQUENCES,
      REQUIRED_COMPAT_CI_JOB_NAMES,
      'REQUIRED_COMPAT_CI_JOB_FIELD_NAME_SEQUENCES',
      { requireExactKeyDomain: true }
    );
    expectKeyedStringRecordDomains(
      REQUIRED_COMPAT_CI_JOB_TOP_LEVEL_SCALAR_VALUE_CONTRACTS,
      REQUIRED_COMPAT_CI_JOB_NAMES,
      'REQUIRED_COMPAT_CI_JOB_TOP_LEVEL_SCALAR_VALUE_CONTRACTS',
      { requireExactKeyDomain: true }
    );
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_JOB_UNIQUE_FIELD_NAMES, 'REQUIRED_COMPAT_CI_JOB_UNIQUE_FIELD_NAMES');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_JOB_FIELD_NAMES, 'REQUIRED_COMPAT_CI_JOB_FIELD_NAMES');
    expect(REQUIRED_COMPAT_CI_JOB_FIELD_NAMES).toEqual(REQUIRED_COMPAT_CI_JOB_UNIQUE_FIELD_NAMES);
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_STEP_SEQUENCE, 'REQUIRED_COMPAT_CI_STEP_SEQUENCE');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_STEP_NAMES, 'REQUIRED_COMPAT_CI_STEP_NAMES');
    expect(REQUIRED_COMPAT_CI_STEP_NAMES).toEqual(REQUIRED_COMPAT_CI_STEP_SEQUENCE);
    expectKeyedStringArrayDomains(
      REQUIRED_COMPAT_CI_JOB_STEP_NAME_SEQUENCES,
      REQUIRED_COMPAT_CI_JOB_NAMES,
      'REQUIRED_COMPAT_CI_JOB_STEP_NAME_SEQUENCES',
      { requireExactKeyDomain: true }
    );
    expectKeyedStringArrayDomains(
      REQUIRED_COMPAT_CI_STEP_FIELD_NAME_SEQUENCES,
      REQUIRED_COMPAT_CI_STEP_NAMES,
      'REQUIRED_COMPAT_CI_STEP_FIELD_NAME_SEQUENCES',
      { requireExactKeyDomain: true, requiredFirstValue: 'name' }
    );
    expectKeyedStringArrayDomains(
      REQUIRED_COMPAT_CI_STEP_WITH_FIELD_NAME_SEQUENCES,
      REQUIRED_COMPAT_CI_STEP_NAMES,
      'REQUIRED_COMPAT_CI_STEP_WITH_FIELD_NAME_SEQUENCES'
    );
    expectKeyedStringArrayDomains(
      REQUIRED_COMPAT_CI_STEP_ENV_FIELD_NAME_SEQUENCES,
      REQUIRED_COMPAT_CI_STEP_NAMES,
      'REQUIRED_COMPAT_CI_STEP_ENV_FIELD_NAME_SEQUENCES'
    );
    expectKeyedStringRecordDomains(
      REQUIRED_COMPAT_CI_STEP_TOP_LEVEL_SCALAR_VALUE_CONTRACTS,
      REQUIRED_COMPAT_CI_STEP_NAMES,
      'REQUIRED_COMPAT_CI_STEP_TOP_LEVEL_SCALAR_VALUE_CONTRACTS',
      { requireExactKeyDomain: true }
    );
    expectKeyedStringRecordDomains(
      REQUIRED_COMPAT_CI_STEP_WITH_SCALAR_VALUE_CONTRACTS,
      REQUIRED_COMPAT_CI_STEP_NAMES,
      'REQUIRED_COMPAT_CI_STEP_WITH_SCALAR_VALUE_CONTRACTS'
    );
    expectKeyedStringRecordDomains(
      REQUIRED_COMPAT_CI_STEP_ENV_SCALAR_VALUE_CONTRACTS,
      REQUIRED_COMPAT_CI_STEP_NAMES,
      'REQUIRED_COMPAT_CI_STEP_ENV_SCALAR_VALUE_CONTRACTS'
    );
  });

  it('keeps required upload artifact file domain unique and non-empty', () => {
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_FILES, 'REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_FILES');
    expect(REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_FILES).toContain('artifact-bundle-validator-result.json');
    expect(REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_FILES).toContain('summary.json');
  });
});
