import { describe, expect, it } from 'vitest';
import {
  REQUIRED_COMPAT_ARTIFACT_PRODUCER_CONSUMER_CONTRACTS,
  REQUIRED_COMPAT_CI_PRIMARY_RUN_COMMAND,
  REQUIRED_COMPAT_CI_FAILURE_UPLOAD_ARTIFACT_NAME,
  REQUIRED_COMPAT_CI_FAILURE_UPLOAD_CONDITION,
  REQUIRED_COMPAT_CI_FAILURE_UPLOAD_IF_NO_FILES_FOUND,
  REQUIRED_COMPAT_CI_FAILURE_UPLOAD_PATH,
  REQUIRED_COMPAT_CI_FAILURE_UPLOAD_STEP_NAME,
  REQUIRED_COMPAT_CI_FAILURE_UPLOAD_USES,
  REQUIRED_COMPAT_CI_WORKFLOW_NAME,
  REQUIRED_COMPAT_CI_WORKFLOW_FIELD_NAMES,
  REQUIRED_COMPAT_CI_WORKFLOW_UNIQUE_FIELD_NAMES,
  REQUIRED_COMPAT_CI_TRIGGER_PUSH_BRANCHES,
  REQUIRED_COMPAT_CI_TRIGGER_NAMES,
  REQUIRED_COMPAT_CI_TRIGGER_SECTION_FIELD_NAME_SEQUENCES,
  REQUIRED_COMPAT_CI_JOB_NAME,
  REQUIRED_COMPAT_CI_JOB_NAMES,
  REQUIRED_COMPAT_CI_JOB_RUNS_ON,
  REQUIRED_COMPAT_CI_JOB_TIMEOUT_MINUTES,
  REQUIRED_COMPAT_CI_JOB_FIELD_NAME_SEQUENCES,
  REQUIRED_COMPAT_CI_JOB_FIELD_NAMES,
  REQUIRED_COMPAT_CI_JOB_STEP_NAME_SEQUENCES,
  REQUIRED_COMPAT_CI_JOB_TOP_LEVEL_SCALAR_VALUE_CONTRACTS,
  REQUIRED_COMPAT_CI_JOB_UNIQUE_FIELD_NAME_SEQUENCES,
  REQUIRED_COMPAT_CI_JOB_UNIQUE_FIELD_NAMES,
  REQUIRED_COMPAT_CI_CHECKOUT_STEP_NAME,
  REQUIRED_COMPAT_CI_CHECKOUT_USES,
  REQUIRED_COMPAT_CI_INSTALL_COMMAND,
  REQUIRED_COMPAT_CI_INSTALL_STEP_NAME,
  REQUIRED_COMPAT_CI_REPORT_DIR_ENV_KEY,
  REQUIRED_COMPAT_CI_REPORT_DIR_ENV_VALUE,
  REQUIRED_COMPAT_CI_SETUP_NODE_CACHE,
  REQUIRED_COMPAT_CI_SETUP_NODE_STEP_NAME,
  REQUIRED_COMPAT_CI_SETUP_NODE_USES,
  REQUIRED_COMPAT_CI_SETUP_NODE_VERSION,
  REQUIRED_COMPAT_CI_STEP_ENV_SCALAR_VALUE_CONTRACTS,
  REQUIRED_COMPAT_CI_STEP_TOP_LEVEL_SCALAR_VALUE_CONTRACTS,
  REQUIRED_COMPAT_CI_STEP_WITH_SCALAR_VALUE_CONTRACTS,
  REQUIRED_COMPAT_CI_STEP_ENV_FIELD_NAME_SEQUENCES,
  REQUIRED_COMPAT_CI_STEP_WITH_FIELD_NAME_SEQUENCES,
  REQUIRED_COMPAT_CI_STEP_FIELD_NAME_SEQUENCES,
  REQUIRED_COMPAT_CI_STEP_NAMES,
  REQUIRED_COMPAT_CI_STEP_SEQUENCE,
  REQUIRED_COMPAT_CI_PRIMARY_RUN_STEP_NAME,
  REQUIRED_COMPAT_CI_REACHABLE_SCRIPT_NAMES,
  REQUIRED_COMPAT_CI_RUN_TARGETS,
  REQUIRED_COMPAT_CI_SEQUENCE,
  REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_NAME,
  REQUIRED_COMPAT_CI_UPLOAD_CONDITION,
  REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_FILES,
  REQUIRED_COMPAT_CI_UPLOAD_IF_NO_FILES_FOUND,
  REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_PATH_PREFIX,
  REQUIRED_COMPAT_CI_UPLOAD_STEP_NAME,
  REQUIRED_COMPAT_CI_UPLOAD_USES,
  REQUIRED_COMPAT_ARTIFACT_CLI_DRIFT_PATHS,
  REQUIRED_COMPAT_ARTIFACT_STACK_RUN_TARGETS,
  REQUIRED_COMPAT_ARTIFACT_STACK_SEQUENCE,
  REQUIRED_COMPAT_NPM_SCRIPT_NAMES,
  REQUIRED_COMPAT_REPORT_STACK_RUN_TARGETS,
  REQUIRED_COMPAT_REPORT_STACK_SEQUENCE,
  REQUIRED_COMPAT_README_CI_ARTIFACTS_LINE_PREFIX,
  REQUIRED_COMPAT_README_PATH,
  REQUIRED_COMPAT_README_SCRIPT_REFERENCE_COMMANDS,
  REQUIRED_COMPAT_SCRIPT_STACK_CONTRACT_TEST_PATHS,
  REQUIRED_COMPAT_SUMMARY_STACK_SEQUENCE,
  REQUIRED_COMPAT_SUMMARY_STACK_RUN_TARGETS,
  REQUIRED_COMPAT_SCRIPT_REFERENCE_SOURCES,
  REQUIRED_COMPAT_VALIDATOR_STACK_RUN_TARGETS,
  REQUIRED_COMPAT_VALIDATOR_STACK_SEQUENCE
} from './compat-npm-script-contracts.mjs';
import {
  expectArrayOfRecordsWithRequiredStringFields,
  expectDistinctStringFieldsPerRecord,
  expectKeyedStringArrayDomains,
  expectKeyedStringRecordDomains,
  expectNonEmptyString,
  expectObjectKeyDomainParity,
  expectNonEmptyUniqueStringArray,
  expectUniqueStringFieldAcrossRecords
} from './compat-contract-assertion-test-utils.js';

describe('compat npm script contracts constants', () => {
  it('keeps required script names unique and non-empty', () => {
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_NPM_SCRIPT_NAMES, 'REQUIRED_COMPAT_NPM_SCRIPT_NAMES');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_REACHABLE_SCRIPT_NAMES, 'REQUIRED_COMPAT_CI_REACHABLE_SCRIPT_NAMES');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_SCRIPT_REFERENCE_SOURCES, 'REQUIRED_COMPAT_SCRIPT_REFERENCE_SOURCES');
    expectNonEmptyUniqueStringArray(
      REQUIRED_COMPAT_README_SCRIPT_REFERENCE_COMMANDS,
      'REQUIRED_COMPAT_README_SCRIPT_REFERENCE_COMMANDS'
    );
    expect(REQUIRED_COMPAT_CI_REACHABLE_SCRIPT_NAMES).toEqual(REQUIRED_COMPAT_NPM_SCRIPT_NAMES);
    expect(REQUIRED_COMPAT_SCRIPT_REFERENCE_SOURCES.every((name) => REQUIRED_COMPAT_NPM_SCRIPT_NAMES.includes(name))).toBe(true);
    expect(
      REQUIRED_COMPAT_README_SCRIPT_REFERENCE_COMMANDS,
      'README command lines must map 1:1 to script reference sources'
    ).toEqual(REQUIRED_COMPAT_SCRIPT_REFERENCE_SOURCES.map((scriptName) => `npm run ${scriptName}`));
  });

  it('keeps required stack sequences and drift paths unique and non-empty', () => {
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_ARTIFACT_CLI_DRIFT_PATHS, 'REQUIRED_COMPAT_ARTIFACT_CLI_DRIFT_PATHS');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_SCRIPT_STACK_CONTRACT_TEST_PATHS, 'REQUIRED_COMPAT_SCRIPT_STACK_CONTRACT_TEST_PATHS');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_FILES, 'REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_FILES');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_ARTIFACT_STACK_SEQUENCE, 'REQUIRED_COMPAT_ARTIFACT_STACK_SEQUENCE');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_ARTIFACT_STACK_RUN_TARGETS, 'REQUIRED_COMPAT_ARTIFACT_STACK_RUN_TARGETS');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_REPORT_STACK_SEQUENCE, 'REQUIRED_COMPAT_REPORT_STACK_SEQUENCE');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_REPORT_STACK_RUN_TARGETS, 'REQUIRED_COMPAT_REPORT_STACK_RUN_TARGETS');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_VALIDATOR_STACK_SEQUENCE, 'REQUIRED_COMPAT_VALIDATOR_STACK_SEQUENCE');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_VALIDATOR_STACK_RUN_TARGETS, 'REQUIRED_COMPAT_VALIDATOR_STACK_RUN_TARGETS');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_SUMMARY_STACK_SEQUENCE, 'REQUIRED_COMPAT_SUMMARY_STACK_SEQUENCE');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_SUMMARY_STACK_RUN_TARGETS, 'REQUIRED_COMPAT_SUMMARY_STACK_RUN_TARGETS');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_SEQUENCE, 'REQUIRED_COMPAT_CI_SEQUENCE');
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_RUN_TARGETS, 'REQUIRED_COMPAT_CI_RUN_TARGETS');
    const requiredScalarStringContracts = [
      [REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_PATH_PREFIX, 'REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_PATH_PREFIX'],
      [REQUIRED_COMPAT_README_PATH, 'REQUIRED_COMPAT_README_PATH'],
      [REQUIRED_COMPAT_README_CI_ARTIFACTS_LINE_PREFIX, 'REQUIRED_COMPAT_README_CI_ARTIFACTS_LINE_PREFIX'],
      [REQUIRED_COMPAT_CI_UPLOAD_STEP_NAME, 'REQUIRED_COMPAT_CI_UPLOAD_STEP_NAME'],
      [REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_NAME, 'REQUIRED_COMPAT_CI_UPLOAD_ARTIFACT_NAME'],
      [REQUIRED_COMPAT_CI_UPLOAD_CONDITION, 'REQUIRED_COMPAT_CI_UPLOAD_CONDITION'],
      [REQUIRED_COMPAT_CI_UPLOAD_USES, 'REQUIRED_COMPAT_CI_UPLOAD_USES'],
      [REQUIRED_COMPAT_CI_UPLOAD_IF_NO_FILES_FOUND, 'REQUIRED_COMPAT_CI_UPLOAD_IF_NO_FILES_FOUND'],
      [REQUIRED_COMPAT_CI_PRIMARY_RUN_STEP_NAME, 'REQUIRED_COMPAT_CI_PRIMARY_RUN_STEP_NAME'],
      [REQUIRED_COMPAT_CI_PRIMARY_RUN_COMMAND, 'REQUIRED_COMPAT_CI_PRIMARY_RUN_COMMAND'],
      [REQUIRED_COMPAT_CI_FAILURE_UPLOAD_STEP_NAME, 'REQUIRED_COMPAT_CI_FAILURE_UPLOAD_STEP_NAME'],
      [REQUIRED_COMPAT_CI_FAILURE_UPLOAD_CONDITION, 'REQUIRED_COMPAT_CI_FAILURE_UPLOAD_CONDITION'],
      [REQUIRED_COMPAT_CI_FAILURE_UPLOAD_ARTIFACT_NAME, 'REQUIRED_COMPAT_CI_FAILURE_UPLOAD_ARTIFACT_NAME'],
      [REQUIRED_COMPAT_CI_FAILURE_UPLOAD_PATH, 'REQUIRED_COMPAT_CI_FAILURE_UPLOAD_PATH'],
      [REQUIRED_COMPAT_CI_FAILURE_UPLOAD_USES, 'REQUIRED_COMPAT_CI_FAILURE_UPLOAD_USES'],
      [REQUIRED_COMPAT_CI_FAILURE_UPLOAD_IF_NO_FILES_FOUND, 'REQUIRED_COMPAT_CI_FAILURE_UPLOAD_IF_NO_FILES_FOUND'],
      [REQUIRED_COMPAT_CI_WORKFLOW_NAME, 'REQUIRED_COMPAT_CI_WORKFLOW_NAME'],
      [REQUIRED_COMPAT_CI_CHECKOUT_STEP_NAME, 'REQUIRED_COMPAT_CI_CHECKOUT_STEP_NAME'],
      [REQUIRED_COMPAT_CI_CHECKOUT_USES, 'REQUIRED_COMPAT_CI_CHECKOUT_USES'],
      [REQUIRED_COMPAT_CI_JOB_NAME, 'REQUIRED_COMPAT_CI_JOB_NAME'],
      [REQUIRED_COMPAT_CI_JOB_RUNS_ON, 'REQUIRED_COMPAT_CI_JOB_RUNS_ON'],
      [REQUIRED_COMPAT_CI_JOB_TIMEOUT_MINUTES, 'REQUIRED_COMPAT_CI_JOB_TIMEOUT_MINUTES'],
      [REQUIRED_COMPAT_CI_SETUP_NODE_STEP_NAME, 'REQUIRED_COMPAT_CI_SETUP_NODE_STEP_NAME'],
      [REQUIRED_COMPAT_CI_SETUP_NODE_USES, 'REQUIRED_COMPAT_CI_SETUP_NODE_USES'],
      [REQUIRED_COMPAT_CI_SETUP_NODE_VERSION, 'REQUIRED_COMPAT_CI_SETUP_NODE_VERSION'],
      [REQUIRED_COMPAT_CI_SETUP_NODE_CACHE, 'REQUIRED_COMPAT_CI_SETUP_NODE_CACHE'],
      [REQUIRED_COMPAT_CI_INSTALL_STEP_NAME, 'REQUIRED_COMPAT_CI_INSTALL_STEP_NAME'],
      [REQUIRED_COMPAT_CI_INSTALL_COMMAND, 'REQUIRED_COMPAT_CI_INSTALL_COMMAND'],
      [REQUIRED_COMPAT_CI_REPORT_DIR_ENV_KEY, 'REQUIRED_COMPAT_CI_REPORT_DIR_ENV_KEY'],
      [REQUIRED_COMPAT_CI_REPORT_DIR_ENV_VALUE, 'REQUIRED_COMPAT_CI_REPORT_DIR_ENV_VALUE']
    ];
    for (const [value, label] of requiredScalarStringContracts) {
      expectNonEmptyString(value, label);
    }
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_WORKFLOW_UNIQUE_FIELD_NAMES, 'REQUIRED_COMPAT_CI_WORKFLOW_UNIQUE_FIELD_NAMES');
    expect(REQUIRED_COMPAT_CI_WORKFLOW_UNIQUE_FIELD_NAMES).toEqual(expect.arrayContaining([
      'name',
      'on',
      'jobs'
    ]));
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_WORKFLOW_FIELD_NAMES, 'REQUIRED_COMPAT_CI_WORKFLOW_FIELD_NAMES');
    expect(REQUIRED_COMPAT_CI_WORKFLOW_FIELD_NAMES).toEqual(REQUIRED_COMPAT_CI_WORKFLOW_UNIQUE_FIELD_NAMES);
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_TRIGGER_PUSH_BRANCHES, 'REQUIRED_COMPAT_CI_TRIGGER_PUSH_BRANCHES');
    expect(REQUIRED_COMPAT_CI_TRIGGER_PUSH_BRANCHES).toEqual(expect.arrayContaining([
      'main',
      'master',
      'cursor/**'
    ]));
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_TRIGGER_NAMES, 'REQUIRED_COMPAT_CI_TRIGGER_NAMES');
    expect(REQUIRED_COMPAT_CI_TRIGGER_NAMES).toEqual(expect.arrayContaining([
      'push',
      'pull_request'
    ]));
    expectKeyedStringArrayDomains(
      REQUIRED_COMPAT_CI_TRIGGER_SECTION_FIELD_NAME_SEQUENCES,
      REQUIRED_COMPAT_CI_TRIGGER_NAMES,
      'REQUIRED_COMPAT_CI_TRIGGER_SECTION_FIELD_NAME_SEQUENCES',
      { requireExactKeyDomain: true, allowEmptyKeys: ['pull_request'] }
    );
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_JOB_NAMES, 'REQUIRED_COMPAT_CI_JOB_NAMES');
    expect(REQUIRED_COMPAT_CI_JOB_NAMES).toContain(REQUIRED_COMPAT_CI_JOB_NAME);
    expectKeyedStringArrayDomains(
      REQUIRED_COMPAT_CI_JOB_UNIQUE_FIELD_NAME_SEQUENCES,
      REQUIRED_COMPAT_CI_JOB_NAMES,
      'REQUIRED_COMPAT_CI_JOB_UNIQUE_FIELD_NAME_SEQUENCES',
      { requireExactKeyDomain: true }
    );
    expectKeyedStringArrayDomains(
      REQUIRED_COMPAT_CI_JOB_FIELD_NAME_SEQUENCES,
      REQUIRED_COMPAT_CI_JOB_NAMES,
      'REQUIRED_COMPAT_CI_JOB_FIELD_NAME_SEQUENCES',
      { requireExactKeyDomain: true }
    );
    expectKeyedStringRecordDomains(
      REQUIRED_COMPAT_CI_JOB_TOP_LEVEL_SCALAR_VALUE_CONTRACTS,
      REQUIRED_COMPAT_CI_JOB_NAMES,
      'REQUIRED_COMPAT_CI_JOB_TOP_LEVEL_SCALAR_VALUE_CONTRACTS',
      { requireExactKeyDomain: true }
    );
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_JOB_UNIQUE_FIELD_NAMES, 'REQUIRED_COMPAT_CI_JOB_UNIQUE_FIELD_NAMES');
    expect(REQUIRED_COMPAT_CI_JOB_UNIQUE_FIELD_NAMES).toEqual(expect.arrayContaining([
      'runs-on',
      'timeout-minutes',
      'steps'
    ]));
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_JOB_FIELD_NAMES, 'REQUIRED_COMPAT_CI_JOB_FIELD_NAMES');
    expect(REQUIRED_COMPAT_CI_JOB_FIELD_NAMES).toEqual(REQUIRED_COMPAT_CI_JOB_UNIQUE_FIELD_NAMES);
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_STEP_SEQUENCE, 'REQUIRED_COMPAT_CI_STEP_SEQUENCE');
    expect(REQUIRED_COMPAT_CI_STEP_SEQUENCE).toEqual(expect.arrayContaining([
      REQUIRED_COMPAT_CI_CHECKOUT_STEP_NAME,
      REQUIRED_COMPAT_CI_SETUP_NODE_STEP_NAME,
      REQUIRED_COMPAT_CI_INSTALL_STEP_NAME,
      REQUIRED_COMPAT_CI_PRIMARY_RUN_STEP_NAME,
      REQUIRED_COMPAT_CI_FAILURE_UPLOAD_STEP_NAME,
      REQUIRED_COMPAT_CI_UPLOAD_STEP_NAME
    ]));
    expectNonEmptyUniqueStringArray(REQUIRED_COMPAT_CI_STEP_NAMES, 'REQUIRED_COMPAT_CI_STEP_NAMES');
    expect(REQUIRED_COMPAT_CI_STEP_NAMES).toEqual(REQUIRED_COMPAT_CI_STEP_SEQUENCE);
    expectKeyedStringArrayDomains(
      REQUIRED_COMPAT_CI_JOB_STEP_NAME_SEQUENCES,
      REQUIRED_COMPAT_CI_JOB_NAMES,
      'REQUIRED_COMPAT_CI_JOB_STEP_NAME_SEQUENCES',
      { requireExactKeyDomain: true }
    );
    expectKeyedStringArrayDomains(
      REQUIRED_COMPAT_CI_STEP_FIELD_NAME_SEQUENCES,
      REQUIRED_COMPAT_CI_STEP_NAMES,
      'REQUIRED_COMPAT_CI_STEP_FIELD_NAME_SEQUENCES',
      { requireExactKeyDomain: true, requiredFirstValue: 'name' }
    );
    expectKeyedStringArrayDomains(
      REQUIRED_COMPAT_CI_STEP_WITH_FIELD_NAME_SEQUENCES,
      REQUIRED_COMPAT_CI_STEP_NAMES,
      'REQUIRED_COMPAT_CI_STEP_WITH_FIELD_NAME_SEQUENCES'
    );
    expectKeyedStringArrayDomains(
      REQUIRED_COMPAT_CI_STEP_ENV_FIELD_NAME_SEQUENCES,
      REQUIRED_COMPAT_CI_STEP_NAMES,
      'REQUIRED_COMPAT_CI_STEP_ENV_FIELD_NAME_SEQUENCES'
    );
    expectKeyedStringRecordDomains(
      REQUIRED_COMPAT_CI_STEP_TOP_LEVEL_SCALAR_VALUE_CONTRACTS,
      REQUIRED_COMPAT_CI_STEP_NAMES,
      'REQUIRED_COMPAT_CI_STEP_TOP_LEVEL_SCALAR_VALUE_CONTRACTS',
      { requireExactKeyDomain: true }
    );
    expectKeyedStringRecordDomains(
      REQUIRED_COMPAT_CI_STEP_WITH_SCALAR_VALUE_CONTRACTS,
      REQUIRED_COMPAT_CI_STEP_NAMES,
      'REQUIRED_COMPAT_CI_STEP_WITH_SCALAR_VALUE_CONTRACTS'
    );
    expectKeyedStringRecordDomains(
      REQUIRED_COMPAT_CI_STEP_ENV_SCALAR_VALUE_CONTRACTS,
      REQUIRED_COMPAT_CI_STEP_NAMES,
      'REQUIRED_COMPAT_CI_STEP_ENV_SCALAR_VALUE_CONTRACTS'
    );
    expectArrayOfRecordsWithRequiredStringFields(
      REQUIRED_COMPAT_ARTIFACT_PRODUCER_CONSUMER_CONTRACTS,
      ['scriptName', 'artifactFile', 'producerSegment', 'consumerSegment'],
      'REQUIRED_COMPAT_ARTIFACT_PRODUCER_CONSUMER_CONTRACTS'
    );
    expectUniqueStringFieldAcrossRecords(
      REQUIRED_COMPAT_ARTIFACT_PRODUCER_CONSUMER_CONTRACTS,
      'artifactFile',
      'REQUIRED_COMPAT_ARTIFACT_PRODUCER_CONSUMER_CONTRACTS artifactFile'
    );
    expectDistinctStringFieldsPerRecord(
      REQUIRED_COMPAT_ARTIFACT_PRODUCER_CONSUMER_CONTRACTS,
      'producerSegment',
      'consumerSegment',
      'REQUIRED_COMPAT_ARTIFACT_PRODUCER_CONSUMER_CONTRACTS segment-distinctness'
    );
  });
});
